### PR TITLE
checkpoint: pyproject.toml draft

### PR DESCRIPTION
**Pull request by gyu-heo**
Major change
- Draft version of the pyproject.toml file using [flit](https://flit.pypa.io/en/stable/).
- The minimum required Python version is set to >=3.11, but feel free to modify the number if needed.
- It seems that flit supports PyPI submission, as mentioned in their [documentation](https://flit.pypa.io/en/latest/cmdline.html#flit-publish). I haven't had the chance to test this functionality yet.

This setup has been verified on the O2 Linux environment. 

For Google Colab, the installation should follow these steps:
Run the command !FLIT_ROOT_INSTALL=1 flit install --user.

### CODE REVIEW

**Comment by RichieHakim** [comment]
- build failed
- stick to `pip install ...`
- if it isn't easy to do, give up or try to make a version that just converts the setup.cfg to pyproject.toml to avoid deprecation errors going forward.

**Comment by gyu-heo** [comment]
Minor change
- Updated pyproject.toml file so that it can replace setup.py and setup.cfg. Build passed.

**Comment by RichieHakim** [comment]
The non-programmatic way that the 'latest' dependencies are being specified makes me want to wait to merge this until we actually have to.

**Comment by gyu-heo** [comment]
Temporarily close this PR

**Pull request closed without merging**
