### PR TITLE
Add checks for warp_sparse_image for diagonal ROIs 

### PR DESCRIPTION
**Pull request by landoskape**
The ``scipy.interpolate.griddata()`` method is used to fill in sparse ROI images. It doesn't work for 1d images. 

The code already includes a check for horizontal and vertical ROIs, but not diagonal ROIs. I added a check for diagonal ROIs to use convolution rather than scipy interpolation. 

Also, I added a fallback if ``griddata()`` fails to just use the convolution again, so that the pipeline doesn't break because one ROI can't be interpolated. 

Here's an example of an ROI that griddata() failed on that is 1-d (it's diagonal). I mean, I probably don't even want that ROI... but I want the pipeline to work :)

image

### CODE REVIEW

**Comment by landoskape** [comment]
> 1. `is_diag` can be computed with fewer computations. Just do
> ```
> is_diag = np.unique(rows - cols).size == 1
> ```

Hm, we can do it in less computations but this isn't right. We want to know if the diffs between each pair of row elements and column elements have the same slope.

$$\large slope_i = \frac{rise_i}{run_i} = \frac{cols[i]-cols[i-1]}{rows[i]-rows[i-1]}$$

So we should just check if ``np.unique(cdiff / rdiff).size == 1`` conditioned on ``not np.any(ridff==0)``

I wrote this out to make sure it's correct from an analytical standpoint. I checked my work by plotting every combination of 3, 4, and 5 points in a 6x6 grid.

**Comment by landoskape** [comment]
I did something that added a bunch of commits on my own active branch. Closing this PR and I just added a commit to the dev branch that reflected our discussion.

**Comment by RichieHakim** [comment]
> > 1. `is_diag` can be computed with fewer computations. Just do
> > 
> > ```
> > is_diag = np.unique(rows - cols).size == 1
> > ```
> 
> Hm, we can do it in less computations but this isn't right. We want to know if the diffs between each pair of row elements and column elements have the same slope.
> 
> slopei=riseiruni=cols[i]−cols[i−1]rows[i]−rows[i−1]
> 
> So we should just check if `np.unique(cdiff / rdiff).size == 1` conditioned on `not np.any(ridff==0)`
> 
> I wrote this out to make sure it's correct from an analytical standpoint. I checked my work by plotting every combination of 3, 4, and 5 points in a 6x6 grid.

Yep. I forgot to consider diagonals with slope != 1. Sorry. Well done again.

I don't love the rdiff condition as it prevents using custom sparse arrays with redundant contiguous values (which I recognize is very rare). A quick google gives something called the 'shoelace algorithm' for computing the area of a set of points. It's 6 array computations, which one less than yours lol. Next time.

**Comment by RichieHakim** [comment]
> The try / except statement has been removed. For what it's worth, I think it would be useful to provide some kind of specific information in the `map_parallel` method (or the methods it calls) about what went wrong. This was pretty hard to debug because I didn't have any familiarity with `griddata()`, so didn't understand the `QHull` exception it raised, and the exception was raised inside of a partial method that was inside of a parallel map.
> 
> I don't see an obvious way to do this systematically, but one thing that would help is for the map_parallel method to pass the index to whatever function it calls, then write a nice error message within the called function that prints the index. For example, add `im_sparse_idx` as an input to `warp_sparse_image`, then have an error message like:
> 
> ```python
> try: 
>     ...
>     griddata()
>     ...
> 
> except Exception as ex:
>     print(f"Error raised in warp_sparse_image for ROI {im_sparse_index}.\n",
>              f"This probably means that scipy's griddata() method cannot handle the structure of ROI {im_sparse_index}.\n",
>              "Try plotting that ROI to figure out why it isn't working.")
>     raise ex
> ```
> 
> This is a big lift because it would likely affect numerous other methods called by map_parallel, so it's just an idea for later if you or anyone else working on ROICaT has time for it.

Yep. Error tracing through mutlthreading sucks. Your suggested solution I think is the correct one. Doing it systematically isn't that hard actually, just tedious. I'll write it up and push it to dev.

**Comment by RichieHakim** [comment]
Pushed. Here is an error stack trace to a failed job. I turned off 'safe' checking of the images in the `warp_sparse_image` subfunction to recreate your experience:

```
Registering ROIs...


Registering ROIs:   0%|                                   | 0/2 [00:00<?, ?it/s]

---------------------------------------------------------------------------
QhullError                                Traceback (most recent call last)
File /media/rich/Home_Linux_partition/github_repos/ROICaT/roicat/helpers.py:3438, in remap_sparse_images.<locals>.warp_sparse_image(im_sparse, remappingIdx, method, fill_value, safe)
   3437 try:
-> 3438     grid_values = scipy.interpolate.griddata(
   3439         points=(rows, cols), 
   3440         values=data, 
   3441         xi=remappingIdx[:,:,::-1], 
   3442         method=method, 
   3443         fill_value=fill_value,
   3444     )
   3445 except Exception as e:

File /media/rich/OS/Users/Richard/Linux_stuff_on_OS/conda_envs/envs/roicat/lib/python3.11/site-packages/scipy/interpolate/_ndgriddata.py:277, in griddata(points, values, xi, method, fill_value, rescale)
    276 elif method == 'cubic' and ndim == 2:
--> 277     ip = CloughTocher2DInterpolator(points, values, fill_value=fill_value,
    278                                     rescale=rescale)
    279     return ip(xi)

File interpnd.pyx:915, in scipy.interpolate.interpnd.CloughTocher2DInterpolator.__init__()

File _qhull.pyx:1827, in scipy.spatial._qhull.Delaunay.__init__()

File _qhull.pyx:353, in scipy.spatial._qhull._Qhull.__init__()

QhullError: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 4)

While executing:  | qhull d Qc Qt Q12 Qz Qbb
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 723615403  delaunay  Qcoplanar-keep  Qtriangulate  Q12-allow-wide
  Qz-infinity-point  Qbbound-last  _pre-merge  _zero-centrum  Qinterior-keep
  _maxoutside  0


During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
File /media/rich/Home_Linux_partition/github_repos/ROICaT/roicat/helpers.py:4330, in map_parallel.<locals>.wrapper(*args_index)
   4329 try:
-> 4330     return func(*args)
   4331 except Exception as e:

File /media/rich/Home_Linux_partition/github_repos/ROICaT/roicat/helpers.py:3446, in remap_sparse_images.<locals>.warp_sparse_image(im_sparse, remappingIdx, method, fill_value, safe)
   3445 except Exception as e:
-> 3446     raise Exception(f"Error interpolating sparse image. Something is either weird about one of the input images or the remappingIdx. Error: {e}")
   3448 # Create a new sparse image from the nonzero pixels

Exception: Error interpolating sparse image. Something is either weird about one of the input images or the remappingIdx. Error: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 4)

While executing:  | qhull d Qc Qt Q12 Qz Qbb
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 723615403  delaunay  Qcoplanar-keep  Qtriangulate  Q12-allow-wide
  Qz-infinity-point  Qbbound-last  _pre-merge  _zero-centrum  Qinterior-keep
  _maxoutside  0


During handling of the above exception, another exception occurred:

ParallelExecutionError                    Traceback (most recent call last)
Cell In[27], line 1
----> 1 aligner.transform_ROIs(
      2     ROIs=data.spatialFootprints, 
      3     remappingIdx=aligner.remappingIdx_nonrigid,
      4     normalize=True,
      5 );

File /media/rich/Home_Linux_partition/github_repos/ROICaT/roicat/tracking/alignment.py:575, in Aligner.transform_ROIs(self, ROIs, remappingIdx, normalize)
    573 self.ROIs_aligned = []
    574 for ii, (remap, rois) in tqdm(enumerate(zip(remappingIdx, ROIs)), total=len(remappingIdx), mininterval=1, disable=not self._verbose, desc='Registering ROIs', position=1):
--> 575     rois_aligned = helpers.remap_sparse_images(
    576         ims_sparse=[roi.reshape((H, W)) for roi in rois],
    577         remappingIdx=remap,
    578         method='cubic',
    579         fill_value=0,
    580         dtype=np.float32,
    581         safe=True,
    582         verbose=False,
    583     )
    584     rois_aligned = scipy.sparse.vstack([roi.reshape(1, -1) for roi in rois_aligned])
    586     if normalize:

File /media/rich/Home_Linux_partition/github_repos/ROICaT/roicat/helpers.py:3454, in remap_sparse_images(ims_sparse, remappingIdx, method, fill_value, dtype, safe, n_workers, verbose)
   3451     return warped_sparse_image
   3453 wsi_partial = partial(warp_sparse_image, remappingIdx=remappingIdx)
-> 3454 ims_sparse_out = map_parallel(func=wsi_partial, args=[ims_sparse,], method='multithreading', workers=n_workers, prog_bar=verbose)
   3455 return ims_sparse_out

File /media/rich/Home_Linux_partition/github_repos/ROICaT/roicat/helpers.py:4351, in map_parallel(func, args, method, workers, prog_bar)
   4348     raise ValueError(f"method {method} not recognized")
   4350 with executor(workers) as ex:
-> 4351     return list(tqdm(ex.map(wrapper, *(args + [indices])), total=n_args, disable=prog_bar!=True))

File /media/rich/OS/Users/Richard/Linux_stuff_on_OS/conda_envs/envs/roicat/lib/python3.11/site-packages/tqdm/std.py:1170, in tqdm.__iter__(self)
   1167 # If the bar is disabled, then just walk the iterable
   1168 # (note: keep this check outside the loop for performance)
   1169 if self.disable:
-> 1170     for obj in iterable:
   1171         yield obj
   1172     return

File /media/rich/OS/Users/Richard/Linux_stuff_on_OS/conda_envs/envs/roicat/lib/python3.11/concurrent/futures/_base.py:619, in Executor.map.<locals>.result_iterator()
    616 while fs:
    617     # Careful not to keep a reference to the popped future
    618     if timeout is None:
--> 619         yield _result_or_cancel(fs.pop())
    620     else:
    621         yield _result_or_cancel(fs.pop(), end_time - time.monotonic())

File /media/rich/OS/Users/Richard/Linux_stuff_on_OS/conda_envs/envs/roicat/lib/python3.11/concurrent/futures/_base.py:317, in _result_or_cancel(***failed resolving arguments***)
    315 try:
    316     try:
--> 317         return fut.result(timeout)
    318     finally:
    319         fut.cancel()

File /media/rich/OS/Users/Richard/Linux_stuff_on_OS/conda_envs/envs/roicat/lib/python3.11/concurrent/futures/_base.py:449, in Future.result(self, timeout)
    447     raise CancelledError()
    448 elif self._state == FINISHED:
--> 449     return self.__get_result()
    451 self._condition.wait(timeout)
    453 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File /media/rich/OS/Users/Richard/Linux_stuff_on_OS/conda_envs/envs/roicat/lib/python3.11/concurrent/futures/_base.py:401, in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

File /media/rich/OS/Users/Richard/Linux_stuff_on_OS/conda_envs/envs/roicat/lib/python3.11/concurrent/futures/thread.py:58, in _WorkItem.run(self)
     55     return
     57 try:
---> 58     result = self.fn(*self.args, **self.kwargs)
     59 except BaseException as exc:
     60     self.future.set_exception(exc)

File /media/rich/Home_Linux_partition/github_repos/ROICaT/roicat/helpers.py:4332, in map_parallel.<locals>.wrapper(*args_index)
   4330     return func(*args)
   4331 except Exception as e:
-> 4332     raise ParallelExecutionError(index, e)

ParallelExecutionError: Job 49 raised an exception: Error interpolating sparse image. Something is either weird about one of the input images or the remappingIdx. Error: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 4)

While executing:  | qhull d Qc Qt Q12 Qz Qbb
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 723615403  delaunay  Qcoplanar-keep  Qtriangulate  Q12-allow-wide
  Qz-infinity-point  Qbbound-last  _pre-merge  _zero-centrum  Qinterior-keep
  _maxoutside  0


```

**Comment by RichieHakim** [comment]
Also I don't see any slow down for full datasets using your diagonal checking code. Brilliant.

Also, reach out sooner with any errors you encounter. No need to suffer and send a beautiful PR.

**Pull request closed without merging**
