### PR TITLE
drawingSelection_revised

### PR DESCRIPTION
**Pull request by gyu-heo**
Minor change
- Scatterplot displays all datapoint
- Plot size is adjustable
- Drawing Selection has LASSO tool only. Other selection tools are removed
- Instructions are updated
- Hyperlinks are fixed

### CODE REVIEW

**Comment by RichieHakim** [comment]
Pull changes from dev to get the new setup.py stuff. You should be able to install with .[classification] and avoid installing hdbscan.

**Comment by RichieHakim** [comment]
Getting this error on import

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-3b434ee0dcfd> in <cell line: 15>()
     13 import numpy as np
     14 import sklearn
---> 15 from umap import UMAP
     16 
     17 import torch

ModuleNotFoundError: No module named 'umap'
```

**Comment by gyu-heo** [comment]
- Failed to replicate UMAP import error
- clustering.py imports optuna, [classification] install leads to this error.

```
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-8-bed303cf463a>](https://localhost:8080/#) in <cell line: 6>()
      4 sys.path.append('/content/ROICaT')
      5 
----> 6 import roicat
      7 
      8 colab_device = set_device()

4 frames
[/content/ROICaT/roicat/tracking/clustering.py](https://localhost:8080/#) in <module>
     11 from tqdm import tqdm
     12 
---> 13 import optuna
     14 import hdbscan
     15 

ModuleNotFoundError: No module named 'optuna'
```

**Comment by gyu-heo** [comment]
Minor change
- optuna and hdbscan in roicat.tracking.classification.py is now imported within a function
- kymatio in scatteringWaveletTransformer.py is now imported within a function
- Colab notebook automatically restarts kernel after ROICaT install
- Colab notebook installs [classification] version of setup.py

**Comment by RichieHakim** [comment]
Lgtm

**Pull request merged**
