### PR TITLE
Holoviews interactive GUI test, 1st version

### PR DESCRIPTION
**Pull request by gyu-heo**
Added a test code for holoview drawing selection function. First draft. Please send me a feedback so that I can fix things.
- First, we deploy holoview layout at bokeh server.
- Then, by using Selenium, we access to that local bokeh server.
- Next, we simulate mouse movement ("drawing") in Chrome browser environment
- Finally, we compare answer to the indices saved at tempfile.

Test passed on local computer.

### CODE REVIEW

**Comment by gyu-heo** [comment]
My bad. We should install selenium too. Will add in requirements.txt.

**Comment by RichieHakim** [comment]
Looks like the runs stalled at the pytest step. Cancelled them after around 3 hours runtume. You may want to write in some comments in the test to see where it is stalling etc.

**Comment by gyu-heo** [comment]
The thread left open caused the pytest to stall. Transition to multiprocessing and ensure all processes are thoroughly cleaned to hopefully resolve the stalling issue.

**Comment by RichieHakim** [comment]
Stalling only happening on Mac now.

**Comment by gyu-heo** [comment]
Some of the tests randomly fail, possibly due to the finicky nature of tempfile in the testing environment. Occasionally, ROInet.zip is not downloaded correctly to the tmp directory (pretty strange). At other times, indices.csv is not generated. The issue is truly stochastic; if we rerun the task, it just resolves itself.

**Comment by RichieHakim** [comment]
Merging without running on my local machine. I'm going to trust that this test is sufficient to trust holoviews dependabot PRs. TYVVVVVVM for figuring this out!

**Comment by RichieHakim** [comment]
ROInet.zip is not downloaded correctly to the tmp directory (pretty strange)
> Why do you think this is? I've never seen it fail on the runners normally.

At other times, indices.csv is not generated
> Any guesses there?

stochastic
> really???? that sucks. are you sure it's stochastic?

**Comment by gyu-heo** [comment]
> ROInet.zip is not downloaded correctly to the tmp directory (pretty strange)
> 
> > Why do you think this is? I've never seen it fail on the runners normally.
> > > This is extremely rare occasion, but I saw this weird event in ubuntu testing environment. Please check **Holoviews interactive GUI test, 1st version #328.** 
Error message as following: =========================== short test summary info ============================
FAILED tests/test_integration.py::test_pipeline_tracking_simple - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ROInet.zip'
============= 1 failed, 9 passed, 23 warnings in 78.03s (0:01:18) ==============
Error: Process completed with exit code 1.


> 
> At other times, indices.csv is not generated
> 
> > Any guesses there?
> 
> stochastic
> 
> > really???? that sucks. are you sure it's stochastic?
> > > At least (by experience) we know this error happens in windows testing environment. I haven't seen the same issue in other environments. However, even within the Windows environment, I can't pinpoint the exact cause. It seems unrelated to whether the context is 'user', 'system', 'all', or 'all_latest'. Moreover, if you simply re-run the failed job, it just succeeds. There's some unpredictable behavior under the hood. We can go over my testing code and chat about it.

**Pull request merged**
